[package]
name = "shellcode_create_remote_thread_dll"
version = "0.1.0"
edition = "2018"
author = "oliv4s"

[dependencies]
kernel32-sys = "0.2.2"
winapi = {version = "0.3.9", features = ["winnt","processthreadsapi","memoryapi","handleapi"] }

[lib]
crate-type = ["cdylib"]
